# Generated by Django 3.0.5 on 2020-05-07 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_task', models.CharField(max_length=25)),
                ('task_significance', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(100)])),
            ],
        ),
    ]
